# CMake generated Testfile for 
# Source directory: D:/Cpp/project/pcg-cpp/test-high
# Build directory: D:/Cpp/project/pcg-cpp/build-test/test-high
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg8_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg8_once_insecure.exe")
  set_tests_properties(check-pcg8_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg8_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg8_once_insecure.exe")
  set_tests_properties(check-pcg8_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg8_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg8_once_insecure.exe")
  set_tests_properties(check-pcg8_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg8_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg8_once_insecure.exe")
  set_tests_properties(check-pcg8_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg8_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg8_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg8_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg8_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg8_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg8_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg8_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg8_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg8_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg8_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg8_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg8_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg8_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg8_oneseq_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg16_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg16_once_insecure.exe")
  set_tests_properties(check-pcg16_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg16_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg16_once_insecure.exe")
  set_tests_properties(check-pcg16_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg16_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg16_once_insecure.exe")
  set_tests_properties(check-pcg16_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg16_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg16_once_insecure.exe")
  set_tests_properties(check-pcg16_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg16_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg16_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg16_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg16_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg16_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg16_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg16_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg16_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg16_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg16_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg16_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg16_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg16_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg16_oneseq_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32.exe")
  set_tests_properties(check-pcg32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32.exe")
  set_tests_properties(check-pcg32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32.exe")
  set_tests_properties(check-pcg32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32.exe")
  set_tests_properties(check-pcg32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_c1024.exe")
  set_tests_properties(check-pcg32_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_c1024.exe")
  set_tests_properties(check-pcg32_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_c1024.exe")
  set_tests_properties(check-pcg32_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_c1024.exe")
  set_tests_properties(check-pcg32_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_c1024 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_c1024_fast.exe")
  set_tests_properties(check-pcg32_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_c1024_fast.exe")
  set_tests_properties(check-pcg32_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_c1024_fast.exe")
  set_tests_properties(check-pcg32_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_c1024_fast.exe")
  set_tests_properties(check-pcg32_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_c1024_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_c64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_c64.exe")
  set_tests_properties(check-pcg32_c64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_c64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_c64.exe")
  set_tests_properties(check-pcg32_c64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_c64 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_c64.exe")
  set_tests_properties(check-pcg32_c64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_c64 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_c64.exe")
  set_tests_properties(check-pcg32_c64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_c64 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_c64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_c64_fast.exe")
  set_tests_properties(check-pcg32_c64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_c64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_c64_fast.exe")
  set_tests_properties(check-pcg32_c64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_c64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_c64_fast.exe")
  set_tests_properties(check-pcg32_c64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_c64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_c64_fast.exe")
  set_tests_properties(check-pcg32_c64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_c64_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_c64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_c64_oneseq.exe")
  set_tests_properties(check-pcg32_c64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_c64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_c64_oneseq.exe")
  set_tests_properties(check-pcg32_c64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_c64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_c64_oneseq.exe")
  set_tests_properties(check-pcg32_c64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_c64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_c64_oneseq.exe")
  set_tests_properties(check-pcg32_c64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_c64_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_fast.exe")
  set_tests_properties(check-pcg32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_fast.exe")
  set_tests_properties(check-pcg32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_fast.exe")
  set_tests_properties(check-pcg32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_fast.exe")
  set_tests_properties(check-pcg32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k1024.exe")
  set_tests_properties(check-pcg32_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k1024.exe")
  set_tests_properties(check-pcg32_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k1024.exe")
  set_tests_properties(check-pcg32_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k1024.exe")
  set_tests_properties(check-pcg32_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k1024 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k1024_fast.exe")
  set_tests_properties(check-pcg32_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k1024_fast.exe")
  set_tests_properties(check-pcg32_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k1024_fast.exe")
  set_tests_properties(check-pcg32_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k1024_fast.exe")
  set_tests_properties(check-pcg32_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k1024_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k16384 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k16384.exe")
  set_tests_properties(check-pcg32_k16384 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k16384 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k16384.exe")
  set_tests_properties(check-pcg32_k16384 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k16384 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k16384.exe")
  set_tests_properties(check-pcg32_k16384 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k16384 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k16384.exe")
  set_tests_properties(check-pcg32_k16384 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k16384 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k16384_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k16384_fast.exe")
  set_tests_properties(check-pcg32_k16384_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k16384_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k16384_fast.exe")
  set_tests_properties(check-pcg32_k16384_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k16384_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k16384_fast.exe")
  set_tests_properties(check-pcg32_k16384_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k16384_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k16384_fast.exe")
  set_tests_properties(check-pcg32_k16384_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k16384_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k2 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k2.exe")
  set_tests_properties(check-pcg32_k2 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k2 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k2.exe")
  set_tests_properties(check-pcg32_k2 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k2 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k2.exe")
  set_tests_properties(check-pcg32_k2 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k2 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k2.exe")
  set_tests_properties(check-pcg32_k2 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k2_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k2_fast.exe")
  set_tests_properties(check-pcg32_k2_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k2_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k2_fast.exe")
  set_tests_properties(check-pcg32_k2_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k2_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k2_fast.exe")
  set_tests_properties(check-pcg32_k2_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k2_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k2_fast.exe")
  set_tests_properties(check-pcg32_k2_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k2_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k64.exe")
  set_tests_properties(check-pcg32_k64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k64.exe")
  set_tests_properties(check-pcg32_k64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k64 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k64.exe")
  set_tests_properties(check-pcg32_k64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k64 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k64.exe")
  set_tests_properties(check-pcg32_k64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k64 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k64_fast.exe")
  set_tests_properties(check-pcg32_k64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k64_fast.exe")
  set_tests_properties(check-pcg32_k64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k64_fast.exe")
  set_tests_properties(check-pcg32_k64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k64_fast.exe")
  set_tests_properties(check-pcg32_k64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k64_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_k64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_k64_oneseq.exe")
  set_tests_properties(check-pcg32_k64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_k64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_k64_oneseq.exe")
  set_tests_properties(check-pcg32_k64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_k64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_k64_oneseq.exe")
  set_tests_properties(check-pcg32_k64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_k64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_k64_oneseq.exe")
  set_tests_properties(check-pcg32_k64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_k64_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_once_insecure.exe")
  set_tests_properties(check-pcg32_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_once_insecure.exe")
  set_tests_properties(check-pcg32_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_once_insecure.exe")
  set_tests_properties(check-pcg32_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_once_insecure.exe")
  set_tests_properties(check-pcg32_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_oneseq.exe")
  set_tests_properties(check-pcg32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_oneseq.exe")
  set_tests_properties(check-pcg32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_oneseq.exe")
  set_tests_properties(check-pcg32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_oneseq.exe")
  set_tests_properties(check-pcg32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg32_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg32_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg32_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg32_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_oneseq_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg32_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg32_unique.exe")
  set_tests_properties(check-pcg32_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg32_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg32_unique.exe")
  set_tests_properties(check-pcg32_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg32_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg32_unique.exe")
  set_tests_properties(check-pcg32_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg32_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg32_unique.exe")
  set_tests_properties(check-pcg32_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg32_unique NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64.exe")
  set_tests_properties(check-pcg64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64.exe")
  set_tests_properties(check-pcg64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64.exe")
  set_tests_properties(check-pcg64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64.exe")
  set_tests_properties(check-pcg64 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_c1024.exe")
  set_tests_properties(check-pcg64_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_c1024.exe")
  set_tests_properties(check-pcg64_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_c1024.exe")
  set_tests_properties(check-pcg64_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_c1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_c1024.exe")
  set_tests_properties(check-pcg64_c1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_c1024 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_c1024_fast.exe")
  set_tests_properties(check-pcg64_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_c1024_fast.exe")
  set_tests_properties(check-pcg64_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_c1024_fast.exe")
  set_tests_properties(check-pcg64_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_c1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_c1024_fast.exe")
  set_tests_properties(check-pcg64_c1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_c1024_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_c32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_c32.exe")
  set_tests_properties(check-pcg64_c32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_c32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_c32.exe")
  set_tests_properties(check-pcg64_c32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_c32 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_c32.exe")
  set_tests_properties(check-pcg64_c32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_c32 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_c32.exe")
  set_tests_properties(check-pcg64_c32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_c32 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_c32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_c32_fast.exe")
  set_tests_properties(check-pcg64_c32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_c32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_c32_fast.exe")
  set_tests_properties(check-pcg64_c32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_c32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_c32_fast.exe")
  set_tests_properties(check-pcg64_c32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_c32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_c32_fast.exe")
  set_tests_properties(check-pcg64_c32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_c32_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_c32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_c32_oneseq.exe")
  set_tests_properties(check-pcg64_c32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_c32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_c32_oneseq.exe")
  set_tests_properties(check-pcg64_c32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_c32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_c32_oneseq.exe")
  set_tests_properties(check-pcg64_c32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_c32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_c32_oneseq.exe")
  set_tests_properties(check-pcg64_c32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_c32_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_fast.exe")
  set_tests_properties(check-pcg64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_fast.exe")
  set_tests_properties(check-pcg64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_fast.exe")
  set_tests_properties(check-pcg64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_fast.exe")
  set_tests_properties(check-pcg64_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_k1024.exe")
  set_tests_properties(check-pcg64_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_k1024.exe")
  set_tests_properties(check-pcg64_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_k1024.exe")
  set_tests_properties(check-pcg64_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_k1024 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_k1024.exe")
  set_tests_properties(check-pcg64_k1024 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_k1024 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_k1024_fast.exe")
  set_tests_properties(check-pcg64_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_k1024_fast.exe")
  set_tests_properties(check-pcg64_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_k1024_fast.exe")
  set_tests_properties(check-pcg64_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_k1024_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_k1024_fast.exe")
  set_tests_properties(check-pcg64_k1024_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_k1024_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_k32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_k32.exe")
  set_tests_properties(check-pcg64_k32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_k32 "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_k32.exe")
  set_tests_properties(check-pcg64_k32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_k32 "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_k32.exe")
  set_tests_properties(check-pcg64_k32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_k32 "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_k32.exe")
  set_tests_properties(check-pcg64_k32 PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_k32 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_k32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_k32_fast.exe")
  set_tests_properties(check-pcg64_k32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_k32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_k32_fast.exe")
  set_tests_properties(check-pcg64_k32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_k32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_k32_fast.exe")
  set_tests_properties(check-pcg64_k32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_k32_fast "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_k32_fast.exe")
  set_tests_properties(check-pcg64_k32_fast PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_k32_fast NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_k32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_k32_oneseq.exe")
  set_tests_properties(check-pcg64_k32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_k32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_k32_oneseq.exe")
  set_tests_properties(check-pcg64_k32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_k32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_k32_oneseq.exe")
  set_tests_properties(check-pcg64_k32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_k32_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_k32_oneseq.exe")
  set_tests_properties(check-pcg64_k32_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_k32_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_once_insecure.exe")
  set_tests_properties(check-pcg64_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_once_insecure.exe")
  set_tests_properties(check-pcg64_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_once_insecure.exe")
  set_tests_properties(check-pcg64_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_once_insecure.exe")
  set_tests_properties(check-pcg64_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_oneseq.exe")
  set_tests_properties(check-pcg64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_oneseq.exe")
  set_tests_properties(check-pcg64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_oneseq.exe")
  set_tests_properties(check-pcg64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_oneseq "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_oneseq.exe")
  set_tests_properties(check-pcg64_oneseq PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_oneseq NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg64_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg64_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg64_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg64_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_oneseq_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg64_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg64_unique.exe")
  set_tests_properties(check-pcg64_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg64_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg64_unique.exe")
  set_tests_properties(check-pcg64_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg64_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg64_unique.exe")
  set_tests_properties(check-pcg64_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg64_unique "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg64_unique.exe")
  set_tests_properties(check-pcg64_unique PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg64_unique NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg128_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg128_once_insecure.exe")
  set_tests_properties(check-pcg128_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg128_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg128_once_insecure.exe")
  set_tests_properties(check-pcg128_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg128_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg128_once_insecure.exe")
  set_tests_properties(check-pcg128_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg128_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg128_once_insecure.exe")
  set_tests_properties(check-pcg128_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg128_once_insecure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(check-pcg128_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Debug/check-pcg128_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg128_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(check-pcg128_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/Release/check-pcg128_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg128_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(check-pcg128_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/MinSizeRel/check-pcg128_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg128_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(check-pcg128_oneseq_once_insecure "D:/Cpp/project/pcg-cpp/build-test/test-high/RelWithDebInfo/check-pcg128_oneseq_once_insecure.exe")
  set_tests_properties(check-pcg128_oneseq_once_insecure PROPERTIES  _BACKTRACE_TRIPLES "D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;25;add_test;D:/Cpp/project/pcg-cpp/test-high/CMakeLists.txt;0;")
else()
  add_test(check-pcg128_oneseq_once_insecure NOT_AVAILABLE)
endif()
